export const colRed: string;
export const colRedText: string;
export const colBlue: string;
export const colBorderBlue: string;
export const colBorderRed: string;
export const colBorderGreen: string;
export const colBorder: string;
export const lightBoxBg: string;
export const darkBoxBg: string;
