export const LOGIN_PAGE = '/login'
export const AUTH_PAGE = '/auth'
export const HOME_PAGE = '/home'
export const HISTORY_PAGE = '/history'
export const ACCOUNT_PAGE = '/account'
export const FORGOT_PWD_PAGE = '/forgot'
export const RESET_PWD_PAGE = '/reset/:token'